version: 2.1
jobs:
  test-x86:
    docker:
      - image: cimg/rust:1.61.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Add target i686-unknown-linux-gnu
          command: |
            rustup target add i686-unknown-linux-gnu
      - restore_cache:
          key: x86-{{ checksum "Cargo.toml" }}
      - run:
          name: Testing x86_64
          command: |
            cargo test --target x86_64-unknown-linux-gnu  -- --nocapture
      - run:
          name: Testing x86
          command: |
            cargo test --target i686-unknown-linux-gnu  -- --nocapture
      - save_cache:
          key: x86-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
            - ./target

workflows:
  test:
    jobs:
      - test-x86